// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"wuyuan_exam/internal/biz"
)

// Injectors from wire.go:

func initTaskUsercase(nodeId int64) (*biz.TaskUsercase, error) {
	bizTaskRepo := NewTaskRepo()
	idGenerator := biz.NewIdGenerator(nodeId)
	taskUsercase := biz.NewTaskUsercase(bizTaskRepo, idGenerator)
	return taskUsercase, nil
}
