// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"wuyuan_exam/internal/biz"
	"wuyuan_exam/internal/data"
	"wuyuan_exam/internal/service"
)

// Injectors from wire.go:

func initTaskService(sqlConn string, nodeId int64, engine *gin.Engine) (*service.TaskService, error) {
	dataData, err := data.NewData(sqlConn)
	if err != nil {
		return nil, err
	}
	taskRepo := data.NewTaskRepo(dataData)
	idGenerator := biz.NewIdGenerator(nodeId)
	taskUsercase := biz.NewTaskUsercase(taskRepo, idGenerator)
	taskService := service.NewTaskService(engine, taskUsercase)
	return taskService, nil
}
